runtime: nodejs14 # or another supported version
instance_class: B2
env: standard
manual_scaling:
  instances: 2
vpc_access_connector:
  name: projects/app-example-gcp/locations/us-west4/connectors/app-example-gcp-connector
